In [9]:
import numpy as np

In [39]:
def data_verificate(input_d, ver_d):
    result = []
    for i in range(0, len(input_d)):#единицы измерения!!!, округления для уменьшения веса файлов 
        #(тут как бы любое число параметров)
#         print(input_d[i])
        print(ver_d[i])
        x = (abs(input_d[i][1]*2.5**2 - ver_d[i][0]))#mu
        print('x={}'.format(x))
        y = (abs(input_d[i][2]*2.5**2 - ver_d[i][1]))#sigma
        print('y={}'.format(y))
        tmp_res = [x, y]
        result.append(np.array(tmp_res))
    return result

In [40]:
def handler(verificate_data):
    global_result = []
    for i in range(0, 100):# поменять на все файлы из папки
        input_data = np.load('current_par_CM_' + str(i) + '.npy', allow_pickle=True)
        print(input_data[1])
        local_result = data_verificate(input_data[1], verificate_data)
        global_result.append(np.array(local_result))
    return global_result

In [41]:
verification_data = []
verification_data.append(np.array([925.9259259,   462.962963]))
verification_data.append(np.array([848.7654321,   385.8024691]))
verification_data.append(np.array([48.61111111,  11.11111111]))
verification_data.append(np.array([0.89, 0.1]))

In [42]:
res = handler(verification_data)
# for i in res:
#     print(i)

[array([1600.74670631,  218.60830962,   19.10673103])
 array([3550.22222917,  333.44009238,   42.0766519 ])
 array([274.85146665,  28.96909989,   3.96325607])
 array([15.99597042,  1.45504921,  0.21351956])]
[925.9259259 462.962963 ]
x=440.3760092389075
y=343.5458940875502
[848.7654321 385.8024691]
x=1235.2351452878124
y=122.82339475057137
[48.61111111 11.11111111]
x=132.44576322147267
y=13.659239306788738
[0.89 0.1 ]
x=8.204057583991545
y=1.2344972279591784
[array([181.68480009,  32.22436412,   8.03250074])
 array([79.1890968 , 59.41619214,  8.13711436])
 array([10.0654893 , 12.35616449,  0.77494629])
 array([1.95208376, 1.3587901 , 0.17486271])]
[925.9259259 462.962963 ]
x=724.5236501267616
y=412.75983336685346
[848.7654321 385.8024691]
x=477.414231223594
y=334.9455043801547
[48.61111111 11.11111111]
x=28.614916928885044
y=6.267696800165588
[0.89 0.1 ]
x=7.602438142405487
y=0.9928919255122485
[array([4730.44613314,   14.70889308,   14.36659384])
 array([807.14679379,  55.10919099,   

In [43]:
res

[array([[4.40376009e+02, 3.43545894e+02],
        [1.23523515e+03, 1.22823395e+02],
        [1.32445763e+02, 1.36592393e+01],
        [8.20405758e+00, 1.23449723e+00]]),
 array([[724.52365013, 412.75983337],
        [477.41423122, 334.94550438],
        [ 28.61491693,   6.2676968 ],
        [  7.60243814,   0.99289193]]),
 array([[8.33995344e+02, 3.73171751e+02],
        [5.04332988e+02, 3.45066203e+02],
        [2.21344302e+01, 2.41938450e+00],
        [6.98854556e+00, 7.59384896e-01]]),
 array([[6.96703483e-02, 3.89171096e+02],
        [6.69277718e+02, 2.31469609e+02],
        [1.04566629e+02, 9.24075779e+00],
        [8.94639642e+00, 1.23548407e+00]]),
 array([[602.9641683 , 411.91702359],
        [441.31968131, 327.87829343],
        [ 25.47133578,   3.22291836],
        [  7.1364203 ,   0.92913315]]),
 array([[ 66.78737407, 369.2603767 ],
        [717.97947787, 176.96007315],
        [110.37117746,  25.38007515],
        [  8.89275453,   2.35755884]]),
 array([[ 302.93446909,  300

In [44]:
len(res)

100

In [45]:
res[0]

array([[4.40376009e+02, 3.43545894e+02],
       [1.23523515e+03, 1.22823395e+02],
       [1.32445763e+02, 1.36592393e+01],
       [8.20405758e+00, 1.23449723e+00]])

In [ ]:
S = []

for i in range(len(res)):
    S.append(res[i])