In [43]:
import numpy as np
import sys

best_arr = []
exp_data = np.array([[925.9, 462.96],
                     [848.8, 385.8],
                     [48.6, 11.1],
                     [0.89, 0.1]])
diff_array = []
sqr_sum_arr = []
min_arr_CM = []


# print(sys.argv[1])      
iters = 200

for i in range(iters):
    model_data = np.load('current_par_CM_{}.npy'.format(i),allow_pickle=True)

    area_diff, CD_diff, diam_diff, ratio_diff = None,None,None,None
    
    for j in range(len(model_data[0])):
        if model_data[0][j] == 'area':
            model_data_area = model_data[1][j][1]*2.5**2
            area_diff = abs(exp_data[0][0] - model_data_area)
        if model_data[0][j] == 'convex_area':
            model_data_CD = model_data[1][j][1]*2.5**2
            CD_diff = abs(exp_data[1][0] - model_data_area)
        if model_data[0][j] == 'diam':
            model_data_diam = model_data[1][j][1]*2.5
            diam_diff = abs(exp_data[2][0] - model_data_area)
        if model_data[0][j] == 'ratio':
            model_data_ratio = model_data[1][j][1]
            ratio_diff = abs(exp_data[3][0] - model_data_area)


    curr_diff_array = np.array([area_diff, CD_diff, diam_diff, ratio_diff])
    diff_array.append(curr_diff_array)
    
    
    if None in curr_diff_array:
        pass
    else:
        sqr_sum_arr.append(0*curr_diff_array[0]**2 + 0*curr_diff_array[1]**2 + 0*curr_diff_array[2]**2 + 
                               curr_diff_array[3]**2)
        min_arr_CM.append(i)
print('CM best iter is {}'.format(min_arr_CM[np.argmin(sqr_sum_arr)]))
print('CM best value is {}'.format(min(sqr_sum_arr)))
best_arr.append(min_arr_CM[np.argmin(sqr_sum_arr)])


exp_data_FB = np.array([[1543, 694],
                     [1620, 694],
                     [71, 14],
                     [0.87, 0.1]])

diff_array = []
sqr_sum_arr = []
min_arr_FB = []


for i in range(iters):
    model_data = np.load('current_par_FB_{}.npy'.format(i),allow_pickle=True)

    area_diff, CD_diff, diam_diff, ratio_diff = None,None,None,None
    
    for j in range(len(model_data[0])):
        if model_data[0][j] == 'area':
            model_data_area = model_data[1][j][1]*2.5**2
            area_diff = abs(exp_data_FB[0][0] - model_data_area)
        if model_data[0][j] == 'convex_area':
            model_data_CD = model_data[1][j][1]*2.5**2
            CD_diff = abs(exp_data_FB[1][0] - model_data_area)
        if model_data[0][j] == 'diam':
            model_data_diam = model_data[1][j][1]*2.5
            diam_diff = abs(exp_data_FB[2][0] - model_data_area)
        if model_data[0][j] == 'ratio':
            model_data_ratio = model_data[1][j][1]
            ratio_diff = abs(exp_data_FB[3][0] - model_data_area)


    curr_diff_array = np.array([area_diff, CD_diff, diam_diff, ratio_diff])
    diff_array.append(curr_diff_array)
    
    
    if None in curr_diff_array:
        pass
    else:
        sqr_sum_arr.append(0*curr_diff_array[0]**2 + 0*curr_diff_array[1]**2 + 0*curr_diff_array[2]**2 + 
                               curr_diff_array[3]**2)
        min_arr_FB.append(i)
        
        
print('FB best iter is {}'.format(min_arr_CM[np.argmin(sqr_sum_arr)]))
print('FB best value is {}'.format(min(sqr_sum_arr)))
best_arr.append(min_arr_FB[np.argmin(sqr_sum_arr)])


np.save('best_arr.npy', best_arr)

CM best iter is 164
CM best value is 546132.6846895963


OSError: Failed to interpret file 'current_par_FB_41.npy' as a pickle

In [31]:
np.load('current_par_FB_7.npy',allow_pickle=True)


array([['area', 'convex_area', 'diam', 'ratio'],
       [array([222.21239886, 259.46138466,  15.08978097]),
        array([1021.31514614,  413.47022135,   43.6118539 ]),
        array([74.04293715, 32.85138224,  5.42266981]),
        array([4.12209556, 1.58399997, 0.19231283])],
       [array([33.36730357,  2.54247316,  2.74273516]),
        array([54.96831731,  2.70234837,  2.72628783]),
        array([10.4684112 ,  0.82083414,  0.97055239]),
        array([0.28277989, 0.01519512, 0.01531085])]], dtype=object)

In [27]:
np.load('current_par_CM_47.npy',allow_pickle=True)

array([['area', 'convex_area', 'diam', 'ratio'],
       [array([470.46495728, 136.72282279,  27.10538188]),
        array([1110.60189821,  215.75904597,   97.58242924]),
        array([83.9443208 , 20.17388846,  6.38924042]),
        array([7.60886018, 1.07454034, 0.58223677])],
       [array([64.99902575,  4.23408626,  4.49851906]),
        array([458.30116979,  41.01324354,  50.91478057]),
        array([13.86138501,  1.17895319,  1.28447619]),
        array([3.44743185, 0.29401094, 0.19253835])]], dtype=object)

In [58]:
diff_array[34]

array([466.60832204, 389.50832204, 410.69167796, 458.40167796])

In [59]:
model_data = np.load('current_par_CM_34.npy',allow_pickle=True)

In [60]:
model_data

array([['area', 'convex_area', 'diam', 'ratio'],
       [array([1353.9261065 ,   73.48666847,   16.64175089]),
        array([3700.43933092,   94.75972968,   26.56539772]),
        array([244.87579954,  13.9493867 ,   1.81113283]),
        array([24.24817082,  1.3165888 ,  0.27173778])],
       [array([115.51090993,   1.63108687,   1.65596028]),
        array([291.52137353,   2.415361  ,   2.41911835]),
        array([30.60478408,  0.25734406,  0.26972643]),
        array([2.66780204, 0.03309405, 0.03689304])]], dtype=object)

In [61]:
exp_data

array([[9.2590e+02, 4.6296e+02],
       [8.4880e+02, 3.8580e+02],
       [4.8600e+01, 1.1100e+01],
       [8.9000e-01, 1.0000e-01]])

In [46]:
len(model_data[0])

3

In [54]:
with open('params.txt', 'r') as params:
    par = params.read()
    par_list = par.split('\n')
for elem in par_list:
    elem = elem.split(',')

In [56]:
par_list[126]

'{69,1001,48.13301671116862,1.0052905814237527,144.7050932696825,10.038743463194487,26.600992367709786,1.8777980948063737,75.67067978967948,12.406167866886866,411.5285963012471,318.27898742671806,0.0,0.0,0.0,0.0,0.0,40.54580161268311,83.06697718356843,13.291272660897578,13.364662317698837}'

In [57]:
len(par_list)

250

In [58]:
par_list[138]

'{97,1001,48.22330511669557,0.9500044996203817,160.95926267503515,10.288908735457344,27.47350939632413,1.1786935308184454,79.53015968199486,11.536407178212052,411.7284503644626,322.0485904958538,0.0,0.0,0.0,0.0,0.0,52.39292841614777,79.29334695815203,16.06655367083992,10.127519854343118}'

In [59]:
par_list[164]

'{45,1001,48.15887848772009,0.9798078406506529,141.1535632713246,10.196108924338139,26.87581070501908,1.8776332100510433,59.22138132185448,11.62165546842588,449.207575362704,303.65460955277604,0.0,0.0,0.0,0.0,0.0,56.31755646392204,72.53324558720183,16.97864861891955,17.062502952404827}'